name: Deploy lab11-saneamento

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copia arquivos para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "index.html,Dockerfile"
          target: "/home/ubuntu/app"

      - name: Build e Deploy na EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app
            docker stop lab11 || true
            docker rm lab11 || true
            docker build -t lab11-saneamento .
            docker run -d -p 80:80 --name lab11 lab11-saneamento
